apiVersion: v1
data: {}
kind: Secret
metadata:
  labels:
    app.kubernetes.io/name: alertmanager-main
  name: alertmanager-kube-rbac-proxy-metric
  namespace: openshift-monitoring
stringData:
  config.yaml: |-
    "authorization":
      "static":
      - "path": "/metrics"
        "resourceRequest": false
        "user":
          "name": "system:serviceaccount:openshift-monitoring:prometheus-k8s"
        "verb": "get"
      - "path": "/federate"
        "resourceRequest": false
        "user":
          "name": "system:serviceaccount:openshift-monitoring:prometheus-k8s-federate"
        "verb": "get"
type: Opaque
